version: '3'

services:

  db2:
    image: postgres
    volumes:
      - postgres_data_interests:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8080
      POSTGRES_DB: interests
    ports:
      - "5454:5432"

  back:
    build: ./backend
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
    ports:
      - "8001:8001"
    depends_on:
      - db2
      - redis
    restart: always

  front:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - back
    restart: always

    depends_on:
      - back
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data_interests:
