version: '3'

services:

  db2:
    image: postgres
    volumes:
      - postgres_data_interests:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8080
      POSTGRES_DB: interests
    ports:
      - "5454:5432"


  back:
    build: ./backend
    command: python manage.py runserver
    ports:
      - "8001:8001"
    depends_on:
      - db2
    restart: always

  front:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - back
    restart: always

  celery_worker:
    build: ./backend
    command: celery -A config worker -l info --logfile=/logs/celery_worker.log
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
    depends_on:
      - back
      - redis

  celery_beat:
    build: ./backend
    command: celery -A config beat -l debug --logfile=/logs/celery_beat.log
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
    depends_on:
      - back
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data_interests:
