services:

  db2:
    image: postgres:16
    volumes:
      - postgres_data_interests:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5454:5432"

  back:
    build: ./backend
    environment:
      CELERY_BROKER_URL: 'redis://redis:6379'
      CELERY_RESULT_BACKEND: 'redis://redis:6379'
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/your-interests.ru/:/etc/letsencrypt/live/your-interests.ru/
    ports:
      - "8001:8001"
    depends_on:
      - db2
      - redis
    restart: always

  front:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always
    depends_on:
      - back
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data_interests:
