# Generated by Django 3.1 on 2020-08-15 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.IntegerField(unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('tmdb_original_name', models.CharField(max_length=200)),
                ('tmdb_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_result', models.CharField(max_length=300)),
                ('action_type', models.CharField(choices=[('score', 'Score changed'), ('review', 'Review changed'), ('status', 'Status changed')], max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('stopped', 'Stopped playing'), ('going', 'Going to play'), ('not watched', 'Not watched')], max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
