# Generated by Django 3.1.1 on 2020-09-04 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='spent_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='action_type',
            field=models.CharField(choices=[('score', 'Score changed'), ('review', 'Review changed'), ('status', 'Status changed'), ('spent_time', 'Spent time changed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('watched', 'Watched'), ('stopped', 'Stopped watching'), ('going', 'Going to watch'), ('not watched', 'Not watched')], max_length=30),
        ),
    ]
