# Generated by Django 3.1.2 on 2020-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200904_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('watched', 'Watched'), ('stopped', 'Stopped watching'), ('going', 'Going to watch'), ('not watched', 'Not watched')], default='not watched', max_length=30),
        ),
    ]
