# Generated by Django 3.1.2 on 2020-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201029_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('watching', 'Смотрю'), ('watched', 'Посмотрел'), ('stopped', 'Дропнул'), ('going', 'Буду смотреть'), ('not watched', 'Не смотрел')], default='not watched', max_length=30),
        ),
    ]
