# Generated by Django 3.1.2 on 2020-12-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201029_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 17, 20, 41, 902886)),
        ),
    ]
