# Generated by Django 3.1.2 on 2020-12-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_usermovie_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 1, 10, 30, 4, 803230, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
