# Generated by Django 3.1.2 on 2020-12-01 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20201201_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
