# Generated by Django 3.1.2 on 2020-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20201201_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='status',
            field=models.CharField(choices=[('watched', 'Посмотрел'), ('stopped', 'Дропнул'), ('going', 'Буду смотреть'), ('not watched', 'Не смотрел')], default='not watched', max_length=30),
        ),
    ]
