# Generated by Django 3.1.5 on 2021-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_genre_moviegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='review',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
