# Generated by Django 3.1.5 on 2021-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20210130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_release_date',
            field=models.DateField(null=True),
        ),
    ]
