# Generated by Django 3.1.6 on 2021-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20210130_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
