# Generated by Django 3.1.6 on 2021-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_tmdb_backdrop_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_backdrop_path',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
