# Generated by Django 4.1.3 on 2022-12-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_movie_tmdb_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
    ]
