# Generated by Django 3.1 on 2020-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_name', models.CharField(max_length=200)),
                ('rawg_id', models.IntegerField()),
                ('hltb_name', models.CharField(max_length=200)),
                ('hltb_id', models.IntegerField()),
            ],
        ),
    ]
