# Generated by Django 3.1 on 2020-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
