# Generated by Django 3.1 on 2020-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200809_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rawg_slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usergamescore',
            name='review',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
