# Generated by Django 3.1 on 2020-08-13 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_auto_20200810_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGameScore',
            new_name='UserGame',
        ),
    ]
