# Generated by Django 3.1 on 2020-08-13 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200813_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('stopped', 'Stopped playing'), ('going', 'Going to play')], default='stopped', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergame',
            name='review',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
