# Generated by Django 3.1 on 2020-08-13 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200813_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hltb_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='hltb_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='review',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
