# Generated by Django 3.1 on 2020-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200814_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
