# Generated by Django 3.1 on 2020-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200814_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
