# Generated by Django 3.1 on 2020-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='message',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
