# Generated by Django 3.1 on 2020-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_gamelog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='message',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='action_result',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelog',
            name='action_type',
            field=models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('stopped', 'Stopped playing'), ('going', 'Going to play')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
