# Generated by Django 3.1 on 2020-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200815_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='action_type',
            field=models.CharField(choices=[('score', 'Score changed'), ('review', 'Review changed'), ('status', 'Status changed')], max_length=30),
        ),
    ]
