# Generated by Django 3.1 on 2020-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200815_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('stopped', 'Stopped playing'), ('going', 'Going to play'), ('not played', 'Not played')], max_length=30),
        ),
    ]
