# Generated by Django 3.1 on 2020-08-19 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200819_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='spent_time',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
