# Generated by Django 3.1 on 2020-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_usergame_spent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='action_type',
            field=models.CharField(choices=[('score', 'Score changed'), ('review', 'Review changed'), ('status', 'Status changed'), ('status', 'Spent time changed')], max_length=30),
        ),
    ]
