# Generated by Django 3.1 on 2020-08-19 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20200819_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='spent_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
