# Generated by Django 3.1.2 on 2020-10-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20201014_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(blank=True, choices=[('playing', 'Играю'), ('completed', 'Прошел'), ('stopped', 'Дропнул'), ('going', 'Буду играть'), ('not played', 'Не играл')], default='not played', max_length=30),
        ),
    ]
