# Generated by Django 3.1.2 on 2020-12-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20201014_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 17, 20, 41, 902886)),
        ),
    ]
