# Generated by Django 3.1.2 on 2020-12-01 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_usergame_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 10, 30, 4, 803230, tzinfo=utc)),
        ),
    ]
