# Generated by Django 3.1.2 on 2020-12-01 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20201201_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 10, 35, 20, 22096, tzinfo=utc)),
        ),
    ]
