# Generated by Django 3.1.4 on 2020-12-07 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20201201_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='spent_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
