# Generated by Django 3.1.4 on 2020-12-08 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20201207_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
