# Generated by Django 3.1.5 on 2021-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_gamegenre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='review',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
