# Generated by Django 3.1.5 on 2021-01-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_game_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='rawg_release_date',
        ),
    ]
