# Generated by Django 3.1.5 on 2021-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_auto_20210130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rawg_release_date',
            field=models.DateField(null=True),
        ),
    ]
