# Generated by Django 3.1.6 on 2021-02-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_auto_20210130_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_tba',
            field=models.BooleanField(default=False),
        ),
    ]
