# Generated by Django 3.1.6 on 2021-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_game_rawg_tba'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
