# Generated by Django 3.2 on 2021-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20210222_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_poster_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
