# Generated by Django 3.2.8 on 2022-11-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_game_rawg_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('rawg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rawg_name', models.CharField(max_length=100)),
                ('rawg_slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.store')),
            ],
            options={
                'unique_together': {('game', 'store')},
            },
        ),
    ]
