# Generated by Django 3.2.8 on 2022-11-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_gamestore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestore',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
