# Generated by Django 4.1.3 on 2022-12-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_gamestore_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game'),
        ),
    ]
