# Generated by Django 4.2.7 on 2026-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_remove_game_rawg_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='red_tigerino_playlist_url',
            field=models.URLField(blank=True),
        ),
    ]
