# Generated by Django 6.0 on 2026-02-28

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('games', '0051_fill_red_tigerino_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_movies_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('preview', models.URLField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('video_max', models.URLField(blank=True, max_length=500)),
                ('video_480', models.URLField(blank=True, max_length=500)),
                ('video_320', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
