# Generated by Django 6.0 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0053_game_trailer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rawg_screenshots_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
