# Generated by Django 6.0.6 on 2026-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0068_game_igdb_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebeattime',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
