# Generated by Django 3.1.4 on 2020-12-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='tmdb_season_number',
            new_name='tmdb_episode_number',
        ),
    ]
