# Generated by Django 3.1.4 on 2020-12-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20201230_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='tmdb_episode_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='tmdb_season_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('tmdb_episode_number', 'tmdb_season')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('tmdb_season_number', 'tmdb_show')},
        ),
    ]
