# Generated by Django 3.1.4 on 2021-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20210101_2329'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                DECLARE
                    constraint_record record;
                BEGIN
                    FOR constraint_record IN
                        SELECT
                            constraint_info.conrelid::regclass AS table_name,
                            constraint_info.conname AS constraint_name
                        FROM pg_constraint constraint_info
                        WHERE constraint_info.contype = 'f'
                            AND constraint_info.confrelid IN (
                                'shows_show'::regclass,
                                'shows_season'::regclass,
                                'shows_episode'::regclass
                            )
                            AND EXISTS (
                                SELECT 1
                                FROM unnest(constraint_info.confkey) AS referenced_key(attnum)
                                JOIN pg_attribute referenced_attribute
                                    ON referenced_attribute.attrelid = constraint_info.confrelid
                                    AND referenced_attribute.attnum = referenced_key.attnum
                                WHERE referenced_attribute.attname = 'id'
                            )
                    LOOP
                        EXECUTE format(
                            'ALTER TABLE %s DROP CONSTRAINT %I',
                            constraint_record.table_name,
                            constraint_record.constraint_name
                        );
                    END LOOP;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
