# Generated by Django 3.1.4 on 2021-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20210101_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
