# Generated by Django 3.1.4 on 2021-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20210101_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershow',
            name='status',
            field=models.CharField(choices=[('watched', 'Посмотрел'), ('stopped', 'Дропнул'), ('going', 'Буду смотреть'), ('not watched', 'Не смотрел'), ('watching', 'Смотрю')], default='not watched', max_length=30),
        ),
    ]
