# Generated by Django 3.1.4 on 2021-01-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_show_tmdb_backdrop_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userepisode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userseason',
            name='updated_at',
        ),
    ]
