# Generated by Django 3.1.4 on 2021-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20210102_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tmdb_backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
