# Generated by Django 3.1.4 on 2021-01-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_genre_moviegenre'),
        ('shows', '0009_auto_20210102_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
            options={
                'unique_together': {('show', 'genre')},
            },
        ),
    ]
