# Generated by Django 3.1.5 on 2021-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_showgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userepisode',
            name='review',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='userseason',
            name='review',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='usershow',
            name='review',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
