# Generated by Django 3.1.5 on 2021-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_episode_tmdb_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tmdb_release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='tmdb_release_date',
            field=models.DateField(null=True),
        ),
    ]
