# Generated by Django 3.1.6 on 2021-02-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_auto_20210130_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tmdb_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('tmdb_season', 'tmdb_episode_number')},
        ),
    ]
