# Generated by Django 3.1.6 on 2021-02-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_auto_20210205_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='tmdb_season_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='tmdb_show',
        ),
    ]
