# Generated by Django 3.1.6 on 2021-02-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_auto_20210209_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tmdb_season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
            preserve_default=False,
        ),
    ]
