# Generated by Django 3.1.6 on 2021-02-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_auto_20210209_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
