# Generated by Django 3.1.6 on 2021-02-13 08:31

from django.db import migrations


def fill_ids(apps, schema_editor):
    ShowModel = apps.get_model('shows', 'Show')
    SeasonModel = apps.get_model('shows', 'Season')
    EpisodeModel = apps.get_model('shows', 'Episode')

    for count, value in enumerate(ShowModel.objects.all()):
        value.id = count + 1
        value.save()

    for count, value in enumerate(SeasonModel.objects.all()):
        value.id = count + 1
        value.save()

    for count, value in enumerate(EpisodeModel.objects.all()):
        value.id = count + 1
        value.save()


class Migration(migrations.Migration):
    dependencies = [
        ('shows', '0020_auto_20210213_1531'),
    ]

    operations = [migrations.RunPython(fill_ids)]
