# Generated by Django 3.1.6 on 2021-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0021_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='fake_tmdb_season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episodelog',
            name='fake_tmdb_episode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='fake_tmdb_show',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seasonlog',
            name='fake_tmdb_season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showgenre',
            name='fake_tmdb_show',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showlog',
            name='fake_tmdb_show',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userepisode',
            name='fake_tmdb_episode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userseason',
            name='fake_tmdb_season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usershow',
            name='fake_show',
            field=models.IntegerField(null=True),
        ),
    ]
