# Generated by Django 3.1.6 on 2021-02-13 08:31

from django.db import migrations


def fill_fks(apps, schema_editor):
    ShowModel = apps.get_model('shows', 'Show')
    SeasonModel = apps.get_model('shows', 'Season')
    EpisodeModel = apps.get_model('shows', 'Episode')
    UserShowModel = apps.get_model('shows', 'UserShow')
    UserSeasonModel = apps.get_model('shows', 'UserSeason')
    UserEpisodeModel = apps.get_model('shows', 'UserEpisode')
    ShowLogModel = apps.get_model('shows', 'ShowLog')
    SeasonLogModel = apps.get_model('shows', 'SeasonLog')
    EpisodeLogModel = apps.get_model('shows', 'EpisodeLog')
    ShowGenreModel = apps.get_model('shows', 'ShowGenre')

    show_mapping = {}
    for model in ShowModel.objects.all():
        show_mapping[model.tmdb_id] = model.id  # map old primary keys to new

    season_mapping = {}
    for model in SeasonModel.objects.all():
        season_mapping[model.tmdb_id] = model.id  # map old primary keys to new

    episode_mapping = {}
    for model in EpisodeModel.objects.all():
        episode_mapping[model.tmdb_id] = model.id  # map old primary keys to new

    for fk_model in SeasonModel.objects.all():
        fk_model.fake_tmdb_show = show_mapping[fk_model.tmdb_show_id]  # change the reference
        fk_model.save()

    for fk_model in EpisodeModel.objects.all():
        fk_model.fake_tmdb_season = season_mapping[fk_model.tmdb_season_id]  # change the reference
        fk_model.save()

    for fk_model in UserShowModel.objects.all():
        fk_model.fake_tmdb_show = show_mapping[fk_model.show_id]  # change the reference
        fk_model.save()

    for fk_model in UserSeasonModel.objects.all():
        fk_model.fake_tmdb_season = season_mapping[fk_model.season_id]  # change the reference
        fk_model.save()

    for fk_model in UserEpisodeModel.objects.all():
        fk_model.fake_tmdb_episode = episode_mapping[fk_model.episode_id]  # change the reference
        fk_model.save()

    for fk_model in ShowLogModel.objects.all():
        fk_model.fake_tmdb_show = show_mapping[fk_model.show_id]  # change the reference
        fk_model.save()

    for fk_model in SeasonLogModel.objects.all():
        fk_model.fake_tmdb_season = season_mapping[fk_model.season_id]  # change the reference
        fk_model.save()

    for fk_model in EpisodeLogModel.objects.all():
        fk_model.fake_tmdb_episode = episode_mapping[fk_model.episode_id]  # change the reference
        fk_model.save()

    for fk_model in ShowGenreModel.objects.all():
        fk_model.fake_tmdb_show = show_mapping[fk_model.show_id]  # change the reference
        fk_model.save()


class Migration(migrations.Migration):
    dependencies = [
        ('shows', '0023_auto_20210213_1606'),
    ]

    operations = [migrations.RunPython(fill_fks)]
