# Generated by Django 3.1.6 on 2021-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0024_shows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='tmdb_season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='tmdb_show',
        ),
        migrations.RemoveField(
            model_name='episodelog',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='seasonlog',
            name='season',
        ),
        migrations.RemoveField(
            model_name='showlog',
            name='show',
        ),
        migrations.AlterUniqueTogether(
            name='showgenre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userepisode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userseason',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usershow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='showgenre',
            name='show',
        ),
        migrations.RemoveField(
            model_name='userepisode',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='userseason',
            name='season',
        ),
        migrations.RemoveField(
            model_name='usershow',
            name='show',
        ),
        migrations.AlterField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
