# Generated by Django 3.1.6 on 2021-02-13 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shows', '0025_auto_20210213_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='fake_tmdb_season',
            new_name='tmdb_season',
        ),
        migrations.RenameField(
            model_name='episodelog',
            old_name='fake_tmdb_episode',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='fake_tmdb_show',
            new_name='tmdb_show',
        ),
        migrations.RenameField(
            model_name='seasonlog',
            old_name='fake_tmdb_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='showgenre',
            old_name='fake_tmdb_show',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='showlog',
            old_name='fake_tmdb_show',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='userepisode',
            old_name='fake_tmdb_episode',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='userseason',
            old_name='fake_tmdb_season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='usershow',
            old_name='fake_tmdb_show',
            new_name='show',
        ),
    ]
