# Generated by Django 3.1.6 on 2021-02-13 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0019_auto_20210130_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0026_auto_20210213_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tmdb_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AlterField(
            model_name='episodelog',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
        migrations.AlterField(
            model_name='season',
            name='tmdb_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
        migrations.AlterField(
            model_name='seasonlog',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AlterField(
            model_name='showgenre',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
        migrations.AlterField(
            model_name='showlog',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
        migrations.AlterField(
            model_name='userepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
        migrations.AlterField(
            model_name='userseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.season'),
        ),
        migrations.AlterField(
            model_name='usershow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('tmdb_season', 'tmdb_episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('tmdb_season_number', 'tmdb_show')},
        ),
        migrations.AlterUniqueTogether(
            name='showgenre',
            unique_together={('show', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='userepisode',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='userseason',
            unique_together={('user', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='usershow',
            unique_together={('user', 'show')},
        ),
    ]
