# Generated by Django 3.1.6 on 2021-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0027_auto_20210213_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='tmdb_backdrop_path',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
