# Generated by Django 3.2 on 2021-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0028_auto_20210222_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
