# Generated by Django 3.2 on 2021-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0029_show_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='tmdb_number_of_episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_status',
            field=models.CharField(blank=True, choices=[('Ended', 'Завершился'), ('Returning Series', 'Продолжается'), ('Pilot', 'Пилот'), ('Canceled', 'Отменен'), ('In Production', 'В производстве'), ('Planned', 'Планируется')], max_length=30),
        ),
    ]
