# Generated by Django 3.2.3 on 2021-05-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0031_show_tmdb_poster_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
    ]
