# Generated by Django 4.1.3 on 2022-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0032_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tmdb_run_time',
            field=models.IntegerField(default=0),
        ),
    ]
