# Generated by Django 4.1.3 on 2022-12-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0034_rename_tmdb_run_time_episode_tmdb_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodelog',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.episode'),
        ),
        migrations.AlterField(
            model_name='seasonlog',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.season'),
        ),
        migrations.AlterField(
            model_name='showlog',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.show'),
        ),
        migrations.AlterField(
            model_name='userepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.episode'),
        ),
        migrations.AlterField(
            model_name='userseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.season'),
        ),
        migrations.AlterField(
            model_name='usershow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.show'),
        ),
    ]
