# Generated by Django 3.1 on 2020-08-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ReformaID', models.IntegerField(null=True)),
                ('ReformaAddress', models.CharField(default=None, max_length=150)),
                ('city', models.CharField(max_length=30, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('HouseWarningType', models.IntegerField(null=True)),
                ('CountALL', models.IntegerField(null=True)),
                ('CountLiv', models.IntegerField(null=True)),
                ('CountUnLiv', models.IntegerField(null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
