export const SET_USER = 'SET_USER';
export const SET_AUTH = "SET_AUTH";
export const SET_LOGINFORM = "SET_LOGINFORM";
export const SET_REGISTRATEFORM = "SET_REGISTRATEFORM";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTRATE_ERROR = "REGISTRATE_ERROR";
