export const SET_USER = 'SET_USER';
export const SET_AUTH = "SET_AUTH";

export const SET_LOGINFORM = "SET_LOGINFORM";
export const SET_REGISTRATEFORM = "SET_REGISTRATEFORM";
export const SET_RESET_PASSWORD_FORM = "SET_RESET_PASSWORD_FORM";

export const SET_CONTENT_GAME = "SET_CONTENT_GAME";
export const SET_CONTENT_GAME_USERINFO = "SET_CONTENT_GAME_USERINFO";
export const SET_CONTENT_GAME_FRIENDS = "SET_CONTENT_GAME_FRIENDS";

export const SET_CONTENT_MOVIE = "SET_CONTENT_MOVIE";
export const SET_CONTENT_MOVIE_USERINFO = "SET_CONTENT_MOVIE_USERINFO";
export const SET_CONTENT_MOVIE_FRIENDS = "SET_CONTENT_MOVIE_FRIENDS";

export const SET_SEARCH_CONTENT_GAMES = "SET_SEARCH_CONTENT_GAMES";
export const SET_SEARCH_CONTENT_MOVIES = "SET_SEARCH_CONTENT_MOVIES";
export const SET_SEARCH_CONTENT_SHOWS = "SET_SEARCH_CONTENT_SHOWS";
export const SET_SEARCH_CONTENT_USERS = "SET_SEARCH_CONTENT_USERS";

export const SET_USER_PAGE_CONTENT = "SET_USER_PAGE_CONTENT";
export const SET_USER_PAGE_FOLLOWING = "SET_USER_PAGE_FOLLOWING";
export const SET_USER_PAGE_LOGs = "SET_USER_PAGE_LOGs";
export const SET_USER_PAGE_FRIENDS_LOGS = "SET_USER_PAGE_FRIENDS_LOGS";

export const SET_IS_LOADING_CONTENT_GAME = "SET_IS_LOADING_CONTENT_GAME";
export const SET_IS_LOADING_CONTENT_GAME_FRIENDS = "SET_IS_LOADING_CONTENT_GAME_FRIENDS";
export const SET_IS_LOADING_CONTENT_MOVIE = "SET_IS_LOADING_CONTENT_MOVIE";
export const SET_IS_LOADING_CONTENT_MOVIE_FRIENDS = "SET_IS_LOADING_CONTENT_MOVIE_FRIENDS";
export const SET_IS_LOADING_SEARCH_GAMES = "SET_IS_LOADING_SEARCH_GAMES";
export const SET_IS_LOADING_SEARCH_MOVIES = "SET_IS_LOADING_SEARCH_MOVIES";
export const SET_IS_LOADING_SEARCH_SHOWS = "SET_IS_LOADING_SEARCH_SHOWS";
export const SET_IS_LOADING_SEARCH_USERS = "SET_IS_LOADING_SEARCH_USERS";
export const SET_IS_LOADING_USER_PAGE_CONTENT = "SET_IS_LOADING_USER_PAGE_CONTENT";
export const SET_IS_LOADING_USER_PAGE_LOGS = "SET_IS_LOADING_USER_PAGE_LOGS";
export const SET_IS_LOADING_USER_PAGE_FRIENDS_LOGS = "SET_IS_LOADING_USER_PAGE_FRIENDS_LOGS";

export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTRATE_ERROR = "REGISTRATE_ERROR";
export const GAME_REQUEST_ERROR = "GAME_REQUEST_ERROR";
export const MOVIE_REQUEST_ERROR = "MOVIE_REQUEST_ERROR";
export const USER_PAGE_ERROR = "USER_PAGE_ERROR";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const CONFIRM_PASSWORD_ERROR = "CONFIRM_PASSWORD_ERROR";