# Generated by Django 3.1 on 2020-08-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
    ]
