# Generated by Django 3.1 on 2020-08-14 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_delete_usergame'),
        ('users', '0005_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlog',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('stopped', 'Stopped playing'), ('going', 'Going to play')], max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
