# Generated by Django 3.1 on 2020-08-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200815_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
