# Generated by Django 3.1.2 on 2020-10-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userfollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='is_active',
            new_name='is_following',
        ),
    ]
