# Generated by Django 3.1.2 on 2020-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201204_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action_type',
            field=models.CharField(choices=[('is_following', 'Follow status changed')], max_length=30),
        ),
    ]
