# Generated by Django 3.1.6 on 2021-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_episodes_release_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_game_release_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_movie_release_email',
            field=models.BooleanField(default=False),
        ),
    ]
