# Generated by Django 3.1.6 on 2021-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210212_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
