# Generated by Django 3.2 on 2021-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy',
            field=models.CharField(choices=[('nobody', 'Никто'), ('all', 'Все'), ('followed', 'Друзья')], default='all', max_length=50),
        ),
    ]
