name: Deploy Application

on:
  push:
    branches:
      - production  # Запускать деплой при пуше в ветку production

jobs:
  deploy:
    runs-on: self-hosted  # Используем self-hosted runner

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Выполняем команды для деплоя
      - name: Deploy via local shell
        run: |
          cd /home/interests/Interests  # Укажите путь до вашего приложения на сервере
          sudo docker compose down
          sudo docker compose build
          sudo docker compose up -d
